import styles from '@/styles/Layout.module.css';
import Head from 'next/head';
import Link from 'next/link';

const Layout = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Car APP</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <Link href={'/'}>
                    <h2>
                        ATE CAR
                    </h2>
                    <p>
                        Choose And Buy a Car
                    </p>
                </Link>
            </header>
            <div className={styles.container}>
                {children}
            </div>
            <footer className={styles.footer}>
                Next.js Practice | ATE CAR Project &copy;
            </footer>
        </div>
    );
};

export default Layout;